# Generated by Django 4.1.4 on 2022-12-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_comentario_fecha_alter_comentario_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='noticia',
            new_name='post',
        ),
    ]
