# Generated by Django 4.1.4 on 2022-12-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miembros',
        ),
    ]
